prepare:
  fetch:
    - url: https://raw.githubusercontent.com/codeclimate/styleguide/master/ruby/rubocop.yml
      path: base_rubocop.yml

    - url: https://raw.githubusercontent.com/codeclimate/styleguide/master/ruby/rails_rubocop.yml
      path: rails_rubocop.yml

engines:
  structure:
    enabled: false
  duplication:
    enabled: false
  rubocop:
    enabled: true
    exclude_paths:
    - "!spec/"
    config:
      file: ".rubocop.yml"
ratings:
  paths:
  - "**.rb"
exclude_paths: []
