inherit_from: rails_rubocop.yml

AllCops:
  TargetRailsVersion: 4.2
  TargetRubyVersion: 2.2

Style/GlobalVars:

Metrics/BlockLength:
  Enabled: true

Metrics/CyclomaticComplexity:
  Enabled: true

Metrics/ParameterLists:
  Enabled: true

Metrics/PerceivedComplexity:
  Enabled: true
